- id: validate-json-schemas
  name: Validate JSON schema files
  entry: validate-json-schemas
  language: python
  files: (^|/|\\)values\.schema\.json$
- id: missing-attributes-schemas
  name: Check for missing attributes in JSON schema files
  entry: missing-attributes-schemas
  language: python
  files: (^|/|\\)values\.schema\.json$
- id: just-fail
  name: Simply fail with a specified given message. Use files/exclude to warn before commit of specific files modifications.
  entry: just-fail
  language: python
