- id: validate-json-schemas
  name: Validate JSON schema files
  entry: validate-json-schemas
  language: python
  files: (^|/|\\)values\.schema\.json$
- id: missing-attributes-schemas
  name: Check for missing attributes in JSON schema files
  entry: missing-attributes-schemas
  language: python
  files: (^|/|\\)values\.schema\.json$
- id: just-fail
  name: Fail if any file matches
  # NOTE: Use files/exclude to warn before commit of specific files modifications.
  entry: just-fail
  language: python
- id: version-bump
  name: Check version bump
  entry: version-bump
  language: python
  pass_filenames: false
  always_run: true
