- id: validate-json-schemas
  name: validate JSON schema files
  entry: validate-json-schemas
  language: python
  files: (^|/|\\)values\.schema\.json$

- id: missing-attributes-schemas
  name: check for missing attributes in JSON schema files
  entry: missing-attributes-schemas
  language: python
  files: (^|/|\\)values\.schema\.json$

- id: check-match
  name: Fails if any staged files matches the given regex
  entry: check-match
  language: python
  pass_filenames: false
  always_run: true

- id: version-bump
  name: check version bump
  entry: version-bump
  language: python
  pass_filenames: false
  always_run: true

- id: helmlint
  name: helmlint
  description: Run helm lint, a linter for helm charts
  entry: sh_hooks/helmlint.sh
  language: script
  files: \.((ya?ml)|(tpl))$
  require_serial: true
